//
//  LTError.h
//  Leadtools Framework
//
//  Copyright © 1991-2016 LEAD Technologies, Inc. All rights reserved.
//

#if defined(__cplusplus)
extern "C" {
#endif // #if defined(__cplusplus)

typedef NS_ENUM(NSInteger, LTError) {
    LTErrorSuccess                                 = 1,
    LTErrorFailure                                 = 0,
    LTErrorSuccessDelete                           = 3,
    LTErrorSuccessRetry                            = 4,
    LTErrorSuccessPartialFailure                   = 8,

    LTErrorKernelExpired                           = -1591,
    LTErrorInvalidParameter                        = -13,
    LTErrorInvalidStructSize                       = -789,
    LTErrorBitsPerPixel                            = -27,
    LTErrorInvalidRange                            = -11,
    LTErrorIncorrectWidthAdjusted                  = -1753,
    LTErrorNoImage                                 = -2,
    LTErrorNullPointer                             = -814,
    LTErrorNotInitialized                          = -30,
    LTErrorSignedDataNotSupported                  = -1360,
    LTErrorBufferTooSmall                          = -290,
    LTErrorException                               = -149,
    LTErrorNothingToDo                             = -351,
    LTErrorImageEmpty                              = -144,
    LTErrorInternal                                = -74,
    LTErrorQFactor                                 = -21,
    LTErrorInvalidHandle                           = -261,
    LTErrorBadPointer                              = -60,
    LTErrorGray32Unsupported                       = -1364,
    LTErrorInvalidLutLength                        = -1486,
    LTErrorInvalidDib                              = -1491,
    LTErrorBitmapFormatUnsupported                 = -1541,

    LTErrorSuccessAbort                            = 2,
    LTErrorUserAbort                               = -100,
    LTErrorNormalAbort                             = -29,

    LTErrorNoMemory                                = -1,
    LTErrorMemoryTooLow                            = -3,

    LTErrorFeatureNotSupported                     = -16,
    LTErrorDocumentNotEnabled                      = -143,
    LTErrorMedicalNotEnabled                       = -314,
    LTErrorProNotEnabled                           = -930,
    LTErrorLzwLocked                               = -146,
    LTErrorJbigNotEnabled                          = -315,
    LTErrorJbig2Locked                             = -1362,
    LTErrorJ2kLocked                               = -542,
    LTErrorPdfNotEnabled                           = -408,
    LTErrorCmwLocked                               = -354,
    LTErrorAbcLocked                               = -1361,
    LTErrorMedicalNetNotEnabled                    = -318,
    LTErrorNitfLocked                              = -1363,
    LTErrorDicomNotEnabled                         = -803,
    LTErrorJpipLocked                              = -1477,
    LTErrorFormsLocked                             = -1478,
    LTErrorDocumentWritersNotEnabled               = -1493,
    LTErrorMediaWriterNotEnabled                   = -1494,
    LTErrorDocumentWritersPdfNotEnabled            = -1495,
    LTErrorLeadPrinterNotEnabled                   = -1535,
    LTErrorLeadPrinterServerNotEnabled             = -1536,
    LTErrorLeadPrinterNetworkNotEnabled            = -1628,
    LTErrorAppStoreNotEnabled                      = -1750,
    LTErrorBasicNotEnabled                         = -1751,
    LTErrorNoServerLicense                         = -1752,

    LTErrorInvalidLicense                          = -1754,
    LTErrorInvalidServerLicense                    = -1755,
    LTErrorUserNotRegisteredForServerLicense       = -1756,
    LTErrorAppNotRegisteredForServerLicense        = -1757,
    LTErrorConnectionToLicenseServerFailed         = -1758,
    LTErrorServerLicenseNotActivated               = -1759,

    LTErrorFileNotFound                            = -10,
    LTErrorFileOpen                                = -14,
    LTErrorFileWrite                               = -5,
    LTErrorFileGone                                = -6,
    LTErrorFileRead                                = -7,
    LTErrorFileSeek                                = -4,
    LTErrorDiskIsFull                              = -295,
    LTErrorFileReadOnly                            = -805,
    LTErrorFileFormat                              = -9,
    LTErrorInvalidFileName                         = -8,
    LTErrorFileCreate                              = -1490,

    LTErrorDxfCodecMissing                         = -309,
    LTErrorJbigCodecMissing                        = -319,
    LTErrorWmfCodecMissing                         = -349,
    LTErrorCmwCodecMissing                         = -355,
    LTErrorCmpCodecMissing                         = -356,
    LTErrorFaxCodecMissing                         = -357,
    LTErrorPdfCodecMissing                         = -358,
    LTErrorTifCodecMissing                         = -359,
    LTErrorDcrCodecMissing                         = -819,
    LTErrorKdcCodecMissing                         = -820,
    LTErrorDcsCodecMissing                         = -821,
    LTErrorAbcCodecMissing                         = -822,
    LTErrorAbiCodecMissing                         = -823,
    LTErrorJb2CodecMissing                         = -824,
    LTErrorJ2kCodecMissing                         = -541,
    LTErrorPngCodecMissing                         = -825,
    LTErrorColorConversionFrameworkMissing         = -807,
    LTErrorVectorKernelMissing                     = -353,
    LTErrorSegmentationFrameworkMissing            = -818,
    LTErrorAnnotationFrameworkMissing              = -1479,
    LTErrorImageProcessingFrameworkMissing         = -1480,
    LTErrorBmpCodecMissing                         = -1496,
    LTErrorRawCodecMissing                         = -1497,
    LTErrorClrCodecMissing                         = -900,
    LTErrorRtfCodecMissing                         = -1537,
    LTErrorPdfEngineMissing                        = -1540,
    LTErrorCgmCodecMissing                         = -1543,
    LTErrorClpCodecMissing                         = -1544,
    LTErrorCrwCodecMissing                         = -1545,
    LTErrorDrwCodecMissing                         = -1547,
    LTErrorDwfCodecMissing                         = -1548,
    LTErrorDwgCodecMissing                         = -1549,
    LTErrorEpsCodecMissing                         = -1550,
    LTErrorFitCodecMissing                         = -1551,
    LTErrorFlcCodecMissing                         = -1552,
    LTErrorGifCodecMissing                         = -1553,
    LTErrorHdpCodecMissing                         = -1554,
    LTErrorIffCodecMissing                         = -1555,
    LTErrorJp2CodecMissing                         = -1556,
    LTErrorJpmCodecMissing                         = -1557,
    LTErrorCinCodecMissing                         = -1558,
    LTErrorLmbCodecMissing                         = -1559,
    LTErrorMifCodecMissing                         = -1560,
    LTErrorMngCodecMissing                         = -1561,
    LTErrorMspCodecMissing                         = -1562,
    LTErrorNtfCodecMissing                         = -1563,
    LTErrorPcdCodecMissing                         = -1564,
    LTErrorPcxCodecMissing                         = -1565,
    LTErrorPsdCodecMissing                         = -1566,
    LTErrorPspCodecMissing                         = -1567,
    LTErrorRasCodecMissing                         = -1568,
    LTErrorSffCodecMissing                         = -1569,
    LTErrorSgiCodecMissing                         = -1570,
    LTErrorSgmCodecMissing                         = -1571,
    LTErrorShpCodecMissing                         = -1572,
    LTErrorSnpCodecMissing                         = -1574,
    LTErrorSvgCodecMissing                         = -1575,
    LTErrorTdbCodecMissing                         = -1576,
    LTErrorTgaCodecMissing                         = -1577,
    LTErrorVecCodecMissing                         = -1578,
    LTErrorVpgCodecMissing                         = -1579,
    LTErrorWfxCodecMissing                         = -1580,
    LTErrorWmzCodecMissing                         = -1581,
    LTErrorWpgCodecMissing                         = -1582,
    LTErrorXpsCodecMissing                         = -1583,
    LTErrorXwdCodecMissing                         = -1584,
    LTErrorItgCodecMissing                         = -1585,
    LTErrorVffCodecMissing                         = -1586,
    LTErrorJxrCodecMissing                         = -1587,
    LTErrorJlsCodecMissing                         = -1588,
    LTErrorDcfCodecMissing                         = -1589,
    LTErrorHtmCodecMissing                         = -1595,
    LTErrorMobCodecMissing                         = -1596,
    LTErrorPubCodecMissing                         = -1597,
    LTErrorIngCodecMissing                         = -1598,
    LTErrorPstCodecMissing                         = -1773,
    LTErrorXmpCodecMissing                         = -1776,
    LTErrorX9fCodecMissing                         = -1777,

    LTErrorNoOverlay                               = -815,
    LTErrorOverlayIndex                            = -816,

    LTErrorWindowSize                              = -28,
    LTErrorInvalidCodecName                        = -1353,
    LTErrorPageNotFound                            = -310,
    LTErrorDeleteLastPage                          = -311,
    LTErrorImageType                               = -12,
    LTErrorBadDecodeState                          = -77,
    LTErrorLayerMissing                            = -800,
    LTErrorOutputType                              = -23,
    LTErrorVersionNumber                           = -78,
    LTErrorChannelMissing                          = -1492,
    LTErrorFileSizeTooBig                          = -1778,
    LTErrorFormatMismatch                          = -1779,
    LTErrorFileInfoUpdated                         = -1780,

    LTErrorJp2Failure                              = -530,
    LTErrorJp2Signature                            = -531,
    LTErrorJp2Unsupported                          = -532,
    LTErrorJ2kFailure                              = -533,
    LTErrorJ2kNoSoc                                = -534,
    LTErrorJ2kNoSot                                = -535,
    LTErrorJ2kInformationSet                       = -536,
    LTErrorJ2kLowTargetSize                        = -537,
    LTErrorJ2kDecompositionLevel                   = -538,
    LTErrorJ2kMarkerValue                          = -539,
    LTErrorJ2kUnsupported                          = -540,
    LTErrorJ2kBoxNotAvailable                      = -1501,

    LTErrorNoStamp                                 = -65,
    LTErrorInvalidStampSize                        = -141,
    LTErrorBadStamp                                = -142,

    LTErrorBadMarker                               = -801,
    LTErrorBadResyncMarker                         = -806,
    LTErrorMarkerSizeTooBig                        = -808,
    LTErrorMarkerMissing                           = -809,
    LTErrorMarkerIndex                             = -811,

    LTErrorAudioMissing                            = -802,
    LTErrorExtensionsMissing                       = -810,

    LTErrorNoChange                                = -145,
    LTErrorImageSize                               = -910,
    LTErrorNoMessage                               = -911,
    LTErrorInvalidPassword                         = -912,
    LTErrorNotEnoughImages                         = -92,

    LTErrorUnknownCompression                      = -15,
    LTErrorCompactAborted                          = -917,
    LTErrorBadTag                                  = -140,
    LTErrorTagMissing                              = -404,

    LTErrorCUBusy                                  = -31,
    LTErrorInvalidTableType                        = -32,
    LTErrorInvalidBuffer                           = -34,
    LTErrorMissingTileData                         = -35,
    LTErrorInvalidQValue                           = -36,
    LTErrorInvalidData                             = -37,
    LTErrorInvalidCompressedType                   = -38,
    LTErrorInvalidComponentNumber                  = -39,
    LTErrorInvalidPixelType                        = -40,
    LTErrorInvalidPixelSampling                    = -41,
    LTErrorInvalidImageDimensions                  = -44,
    LTErrorInvalidTileDimension                    = -45,
    LTErrorInvalidPixBufferDimensions              = -46,
    LTErrorSegmentOverflow                         = -47,
    LTErrorInvalidSubsampling                      = -48,
    LTErrorInvalidQVisTable                        = -49,
    LTErrorInvalidDCCodeTable                      = -50,
    LTErrorInvalidACCodeTable                      = -51,
    LTErrorInsufficientData                        = -52,
    LTErrorMissingFunctionPointer                  = -53,
    LTErrorTooManyDCCodeTables                     = -54,
    LTErrorTooManyACCodeTables                     = -55,
    LTErrorInvalidSubImage                         = -56,
    LTErrorInvalidAbortion                         = -57,
    LTErrorCUNoSupport                             = -58,
    LTErrorCUFailure                               = -59,
    LTErrorCompressedDataFailure                   = -62,

    LTErrorInvalidColorspace                       = -918,
    LTErrorInvalidFormat                           = -785,
    LTErrorUnsupportedMethod                       = -786,
    LTErrorOpeningProfile                          = -787,
    LTErrorInvalidColorProfile                     = -788,
    LTErrorUVNotMultiples                          = -791,
    LTErrorNoNonplanarVerticalSubsamplingSupported = -792,
    LTErrorPlanarAlignmentNotSupported             = -793,
    LTErrorUnsupportedConversion                   = -794,
    LTErrorTruncateHeight                          = -795,
    LTErrorTruncateWidth                           = -796,
    LTErrorTruncateWidthAndHeight                  = -797,

    LTErrorICCUnknownTag                           = -1150,
    LTErrorICCUnknownType                          = -1151,
    LTErrorICCUnknownTagAndType                    = -1152,
    LTErrorInvalidICCProfile                       = -1153,
    LTErrorICCImageNotSupported                    = -1154,
    LTErrorNoProfile                               = -812,
    LTErrorCorruptProfile                          = -817,
    LTErrorDecodingProfile                         = -813,

    LTErrorPdfFileEncrypted                        = -721,
    LTErrorPdfInvalidPassword                      = -722,
    LTErrorPdfFaxNotEnabled                        = -723,
    LTErrorPdfJpegNotEnabled                       = -724,
    LTErrorPdfInvDocStructuringComments            = -725,
    LTErrorPdfFontsDirectoryNotFound               = -726,
    LTErrorPdfCannotEditFile                       = -727,
    LTErrorPdfBadContent                           = -728,
    LTErrorPdfBadInitializationFiles               = -729,
    LTErrorPdfBadInterpageLinks                    = -1599,

    LTErrorPreProcessBadState                      = -1503,
    LTErrorPreProcessInit                          = -1504,
    LTErrorPreProcessCantScaleEdgeSteps            = -1505,
    LTErrorPreProcessWrongWord                     = -1506,
    LTErrorPreProcessCantFindPointBand             = -1507,
    LTErrorPreProcessUnmatchedBlockRight           = -1508,
    LTErrorPreProcessUnmatchedBlockLeft            = -1509,
    LTErrorPreProcessUnmatchedBlockRightRemaining  = -1510,
    LTErrorPreProcessCodesIllegalsum               = -1511,
    LTErrorPreProcessIllegalSampleSize             = -1512,
    LTErrorPreProcessIllegalCircularSpec           = -1513,
    LTErrorPreProcessIllegalEssentialSpec          = -1514,
    LTErrorPreProcessIllegalMinMaxSpec             = -1515,
    LTErrorPreProcessIllegalSampleCount            = -1516,
    LTErrorPreProcessIllegalMeadnSpec              = -1517,
    LTErrorPreProcessIllegalVarianceSpec           = -1518,
    LTErrorPreProcessIllegalDistribution           = -1519,
    LTErrorPreProcessIllegalSignificanceSpec       = -1520,
    LTErrorPreProcessIllegalStyleSpec              = -1521,
    LTErrorPreProcessIllegalFloat                  = -1522,
    LTErrorPreProcessIllegalNumSets                = -1523,
    LTErrorPreProcessIllegalShortName              = -1524,
    LTErrorPreProcessIllegalFeatureParam           = -1525,
    LTErrorPreProcessIllegalNumFeatures            = -1526,
    LTErrorPreProcessHeapFull                      = -1527,
    LTErrorPreProcessIllegalAmbiguitySpecification = -1528,
    LTErrorPreProcessInvalidUnicodeCharset         = -1529,
    LTErrorPreProcessBadOkMode                     = -1530,
    LTErrorPreProcessBadRejectMode                 = -1531,
    LTErrorPreProcessReadingTemplateFile           = -1532,
    LTErrorPreProcessReadingEdgesFile              = -1533,
    LTErrorPreProcessCantOpenChoiceFile            = -1534,

    LTErrorMedicalViewerActionNotAdded             = -1538,
    LTErrorMedicalViewerActionAlreadyAdded         = -1539,

    LTErrorSvgFileSizeRead                         = -770,
    LTErrorSvgRootNotFound                         = -771,
    LTErrorSvgInvalidElement                       = -773,
    LTErrorSvgDuplicatedAttribute                  = -774,
    LTErrorSvgInvalidAttribute                     = -775,
    LTErrorSvgInvalidAttributeValue                = -776,
    LTErrorSvgBadCssProperty                       = -777,
    LTErrorSvgMissingRequiredAttribute             = -778,
    LTErrorSvgDuplicatedID                         = -779,
    LTErrorSvgInvalidCoordinatesNumber             = -780,
    LTErrorSvgInvalidStringComma                   = -781,
    LTErrorSvgAttributeNotFound                    = -782,
    LTErrorSvgFileNotFlat                          = -783,

    LTErrorOcrNotEnabled                           = -1760,
    LTErrorOcrPdfNotEnabled                        = -1761,
    LTErrorOcrOmrNotEnabled                        = -1762,
    LTErrorOcrEngineNotStarted                     = -1763,
    LTErrorOcrLanguageNotSupported                 = -1764,
    LTErrorOcrComponentMissing                     = -1765,
    LTErrorOcrInvalidSettingName                   = -1766,
    LTErrorOcrInvalidSettingType                   = -1767,
    LTErrorOcrInvalidSettingValue                  = -1768,
    LTErrorOcrInvalidZoneType                      = -1769,
    LTErrorOcrInitialization                       = -1770,
    LTErrorOcrError                                = -1771,
    LTErrorOcrSpellcheckerNotFound                 = -1772,
    LTErrorOcrMultipleAsianLanguagesNotAllowed     = -1774,
};
    
NS_ASSUME_NONNULL_BEGIN
    
extern NSString * const LTErrorDomain;
extern NSString * const LeadtoolsException;

NSError *LTErrorWithCode(NSInteger code);
NSException *LTExceptionWithCode(NSInteger code);
    
NS_ASSUME_NONNULL_END
    
#if defined(__cplusplus)
}
#endif // #if defined(__cplusplus)
